apiVersion: batch/v1beta1
kind: CronJob
metadata:
  annotations:
    openshift.io/scc: privileged
  labels:
    cluster: sec-context
    schedule: 0_NE1_N_N_N
    type: cron
  name: adc5a-each-hour-pvc
  ownerReferences:
    - controller: true
      kind: PerconaXtraDBCluster
      name: sec-context
spec:
  concurrencyPolicy: Allow
  failedJobsHistoryLimit: 1
  jobTemplate:
    metadata:
      ownerReferences:
        - apiVersion: batch/v1beta1
          kind: CronJob
          name: adc5a-each-hour-pvc
    spec:
      template:
        metadata:
          annotations:
            openshift.io/scc: privileged
          labels:
            cluster: sec-context
            schedule: 0_NE1_N_N_N
            type: cron
        spec:
          containers:
            - args:
                - sh
                - -c
                - "\n\t\t\t\t\t\t\tcat <<-EOF | kubectl apply -f -\n\t\t\t\t\t\t\t\t\tapiVersion: pxc.percona.com/v1\n\t\t\t\t\t\t\t\t\tkind: PerconaXtraDBClusterBackup\n\t\t\t\t\t\t\t\t\tmetadata:\n\t\t\t\t\t\t\t\t\t  name: \"cron-${pxcCluster:0:16}-pvc-$(date -u \"+%Y%m%d%H%M%S\")-${suffix}\"\n\t\t\t\t\t\t\t\t\t  labels:\n\t\t\t\t\t\t\t\t\t    ancestor: \"adc5a-each-hour-pvc\"\n\t\t\t\t\t\t\t\t\t    cluster: \"${pxcCluster}\"\n\t\t\t\t\t\t\t\t\t    type: \"cron\"\n\t\t\t\t\t\t\t\t\tspec:\n\t\t\t\t\t\t\t\t\t  pxcCluster: \"${pxcCluster}\"\n\t\t\t\t\t\t\t\t\t  storageName: \"pvc\"\n\t\t\t\t\t\t\tEOF\n\t\t\t\t\t\t\t"
              env:
                - name: pxcCluster
                  value: sec-context
              imagePullPolicy: Always
              name: run-backup
              resources: {}
              securityContext:
                privileged: true
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
          dnsPolicy: ClusterFirst
          restartPolicy: Never
          schedulerName: default-scheduler
          securityContext:
            fsGroup: 1001
            supplementalGroups:
              - 1001
              - 1002
              - 1003
          serviceAccount: percona-xtradb-cluster-operator
          serviceAccountName: percona-xtradb-cluster-operator
          terminationGracePeriodSeconds: 30
  schedule: 0 */1 * * *
  successfulJobsHistoryLimit: 1
  suspend: false
